# This caller workflow tests, builds, and pushes the image to Docker Hub.

name: Test, build and push

on: push

jobs:

  test:
    uses: SarahNadeau/docker-playground/.github/workflows/test.yml@master
    with:
      path_to_context: "./test_python_example"

  build-and-push:
    needs: test  # this jobs needs to run serially, after testing succeeded
    uses: SarahNadeau/docker-playground/.github/workflows/build.yml@master
    with:
      path_to_context: "./test_python_example"
    secrets:
      docker_hub_username: ${{ secrets.DOCKER_HUB_USERNAME }}
      docker_hub_access_token: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
