# This caller workflow test, builds, and pushes the image to Docker Hub.

name: Build and push

on: push

jobs:

  test:
    uses: SarahNadeau/docker-playground/.github/workflows/test.yml@main
    with:
      path_to_context: "./test_python_example"

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      # See https://docs.docker.com/engine/reference/commandline/buildx_build/
      # And https://evilmartians.com/chronicles/build-images-on-github-actions-with-docker-layer-caching
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-multi-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-multi-buildx

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./test_python_example
          file: ./test_python_example/Dockerfile
          target: app
          push: true
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,mode=max,dest=/tmp/.buildx-cache-new. # mode=max means export layers from all stage to cache
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/test_python_example:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

        # This apparently prevents the cache from growing in size forever
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache