# This caller workflow builds an image to the "test" stage.
# Instructions: replace all the <placeholder> stubs in this template with values for your image.
# Some explanations come from: https://github.com/actions/starter-workflows/blob/main/automation/manual.yml

name: Test Git LFS with docker by building image

# Controls when the action will run. Workflow runs when manually triggered using the UI or when you submit your pull request
on: [workflow_dispatch, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # This job calls a workflow to build the image to the 'test' stage
  build-to-test:
    uses: SarahNadeau/docker-playground/.github/workflows/build-to-test.yml@master
    with:
      path_to_context: "git-lfs-with-docker"  # Path to directory with Dockerfile and context, e.g. "./spades/3.12.0"
      cache: "git-lfs-test"