name: Build and push docker image to Docker Hub

on:
  push:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest
      
    steps:
    - name: Check Out Repo 
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: Build to test
      run: docker build --target test test_python_example/
      
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: ./test_python_example
        file: ./test_python_example/Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/test_python_example:latest

    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
