# This called workflow builds a docker container, targeting the "test" stage.
# TODO: need to include container-specific element to cache key?
# TODO: move check out repo to another called workflow, or need to repeat this step?

name: Build to test

on:
  workflow_call:
    inputs:
      path_to_context:
        required: true
        type: string
      dockerfile_name:
        default: Dockerfile
        required: false
        type: string

jobs:
  build_to_test:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build to test
        id: docker_build_to_test
        uses: docker/build-push-action@v2
        with:
          context: ${{ inputs.path_to_context }}
          file: ${{ inputs.path_to_context }}/${{ inputs.dockerfile_name }}
          target: test
          push: false
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,mode=max,dest=/tmp/.buildx-cache-new

      - name: Move cache
        # This apparently prevents the cache from growing in size forever
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
